// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaivfrOeUVUgbmr13BI61sxjdud-7B2pE',
    appId: '1:1085659498297:web:62ff397d7b15a7bb000ae8',
    messagingSenderId: '1085659498297',
    projectId: 'iqj-uniapp',
    authDomain: 'iqj-uniapp.firebaseapp.com',
    storageBucket: 'iqj-uniapp.appspot.com',
    measurementId: 'G-9DMG4LLB5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVlz2pRezVz2ovO9xvMB_tTyjTeraOC8',
    appId: '1:1085659498297:android:d4c8e9feed28a9c2000ae8',
    messagingSenderId: '1085659498297',
    projectId: 'iqj-uniapp',
    storageBucket: 'iqj-uniapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyv_mIY7rVonNJE4C_aCHHKsNzQ1CC0vI',
    appId: '1:1085659498297:ios:99e79a16cadc31ee000ae8',
    messagingSenderId: '1085659498297',
    projectId: 'iqj-uniapp',
    storageBucket: 'iqj-uniapp.appspot.com',
    iosBundleId: 'com.example.iqj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyv_mIY7rVonNJE4C_aCHHKsNzQ1CC0vI',
    appId: '1:1085659498297:ios:99e79a16cadc31ee000ae8',
    messagingSenderId: '1085659498297',
    projectId: 'iqj-uniapp',
    storageBucket: 'iqj-uniapp.appspot.com',
    iosBundleId: 'com.example.iqj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaivfrOeUVUgbmr13BI61sxjdud-7B2pE',
    appId: '1:1085659498297:web:86e8e14c345ec300000ae8',
    messagingSenderId: '1085659498297',
    projectId: 'iqj-uniapp',
    authDomain: 'iqj-uniapp.firebaseapp.com',
    storageBucket: 'iqj-uniapp.appspot.com',
    measurementId: 'G-R9SHN7H5M1',
  );
}
